use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Class, Interface, Extends, Implements, Abstract, Virtual,
    Override, Final, Static, Public, Private, Reflectable,
    New, Delete, Null, True, False,
    If, Else, For, While, Return, Break, Continue,
    Try, Catch, Throw, Import, Package, Extern,
    Sizeof, TypeId, This, Super, InstanceOf,
    At, As, Finally,
    Enum, Match, Switch, Case, Default, In,

    Void, Bool, Byte, Char, Short, Int, Long, Float, Double,

    Identifier(String),
    IntegerLiteral(i64),
    FloatLiteral(f64),
    StringLiteral(String),
    CharLiteral(char),

    Plus, Minus, Star, Slash, Percent,
    Amp, Pipe, Caret, Tilde,
    Lt, Gt, Le, Ge, Eq, Ne,
    And, Or, Not,
    Assign, PlusAssign, MinusAssign,
    StarAssign, SlashAssign, PercentAssign,
    AndAssign, OrAssign, XorAssign,
    Shl, Shr,
    ShlAssign, ShrAssign,
    Inc, Dec,
    Arrow, FatArrow,

    LeftParen, RightParen,
    LeftBrace, RightBrace,
    LeftBracket, RightBracket,
    Comma, Dot, Semicolon, Colon, Question,

    EndOfFile,
    Error(String),
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Span {
    pub start: usize,
    pub end: usize,
    pub line: usize,
    pub column: usize,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Class => write!(f, "class"),
            TokenKind::Interface => write!(f, "interface"),
            TokenKind::Extends => write!(f, "extends"),
            TokenKind::Implements => write!(f, "implements"),
            TokenKind::Abstract => write!(f, "abstract"),
            TokenKind::Virtual => write!(f, "virtual"),
            TokenKind::Override => write!(f, "override"),
            TokenKind::Final => write!(f, "final"),
            TokenKind::Static => write!(f, "static"),
            TokenKind::Public => write!(f, "public"),
            TokenKind::Private => write!(f, "private"),
            TokenKind::Reflectable => write!(f, "reflectable"),
            TokenKind::New => write!(f, "new"),
            TokenKind::Delete => write!(f, "delete"),
            TokenKind::Null => write!(f, "null"),
            TokenKind::True => write!(f, "true"),
            TokenKind::False => write!(f, "false"),
            TokenKind::If => write!(f, "if"),
            TokenKind::Else => write!(f, "else"),
            TokenKind::For => write!(f, "for"),
            TokenKind::While => write!(f, "while"),
            TokenKind::Return => write!(f, "return"),
            TokenKind::Break => write!(f, "break"),
            TokenKind::Continue => write!(f, "continue"),
            TokenKind::Try => write!(f, "try"),
            TokenKind::Catch => write!(f, "catch"),
            TokenKind::Throw => write!(f, "throw"),
            TokenKind::Import => write!(f, "import"),
            TokenKind::Package => write!(f, "package"),
            TokenKind::Extern => write!(f, "extern"),
            TokenKind::Sizeof => write!(f, "sizeof"),
            TokenKind::TypeId => write!(f, "typeid"),
            TokenKind::This => write!(f, "this"),
            TokenKind::Super => write!(f, "super"),
            TokenKind::InstanceOf => write!(f, "instanceof"),
            TokenKind::At => write!(f, "@"),
            TokenKind::As => write!(f, "as"),
            TokenKind::Finally => write!(f, "finally"),
            TokenKind::Enum => write!(f, "enum"),
            TokenKind::Match => write!(f, "match"),
            TokenKind::Switch => write!(f, "switch"),
            TokenKind::Case => write!(f, "case"),
            TokenKind::Default => write!(f, "default"),
            TokenKind::In => write!(f, "in"),
            TokenKind::Void => write!(f, "void"),
            TokenKind::Bool => write!(f, "bool"),
            TokenKind::Byte => write!(f, "byte"),
            TokenKind::Char => write!(f, "char"),
            TokenKind::Short => write!(f, "short"),
            TokenKind::Int => write!(f, "int"),
            TokenKind::Long => write!(f, "long"),
            TokenKind::Float => write!(f, "float"),
            TokenKind::Double => write!(f, "double"),
            TokenKind::Identifier(s) => write!(f, "Identifier({})", s),
            TokenKind::IntegerLiteral(i) => write!(f, "Int({})", i),
            TokenKind::FloatLiteral(v) => write!(f, "Float({})", v),
            TokenKind::StringLiteral(s) => write!(f, "String({:?})", s),
            TokenKind::CharLiteral(c) => write!(f, "Char({})", c),
            TokenKind::Plus => write!(f, "+"),
            TokenKind::Minus => write!(f, "-"),
            TokenKind::Star => write!(f, "*"),
            TokenKind::Slash => write!(f, "/"),
            TokenKind::Percent => write!(f, "%"),
            TokenKind::Amp => write!(f, "&"),
            TokenKind::Pipe => write!(f, "|"),
            TokenKind::Caret => write!(f, "^"),
            TokenKind::Tilde => write!(f, "~"),
            TokenKind::Lt => write!(f, "<"),
            TokenKind::Gt => write!(f, ">"),
            TokenKind::Le => write!(f, "<="),
            TokenKind::Ge => write!(f, ">="),
            TokenKind::Eq => write!(f, "=="),
            TokenKind::Ne => write!(f, "!="),
            TokenKind::And => write!(f, "&&"),
            TokenKind::Or => write!(f, "||"),
            TokenKind::Not => write!(f, "!"),
            TokenKind::Assign => write!(f, "="),
            TokenKind::PlusAssign => write!(f, "+="),
            TokenKind::MinusAssign => write!(f, "-="),
            TokenKind::StarAssign => write!(f, "*="),
            TokenKind::SlashAssign => write!(f, "/="),
            TokenKind::PercentAssign => write!(f, "%="),
            TokenKind::AndAssign => write!(f, "&="),
            TokenKind::OrAssign => write!(f, "|="),
            TokenKind::XorAssign => write!(f, "^="),
            TokenKind::Shl => write!(f, "<<"),
            TokenKind::Shr => write!(f, ">>"),
            TokenKind::ShlAssign => write!(f, "<<="),
            TokenKind::ShrAssign => write!(f, ">>="),
            TokenKind::Inc => write!(f, "++"),
            TokenKind::Dec => write!(f, "--"),
            TokenKind::Arrow => write!(f, "->"),
            TokenKind::FatArrow => write!(f, "=>"),
            TokenKind::LeftParen => write!(f, "("),
            TokenKind::RightParen => write!(f, ")"),
            TokenKind::LeftBrace => write!(f, "{{"),
            TokenKind::RightBrace => write!(f, "}}"),
            TokenKind::LeftBracket => write!(f, "["),
            TokenKind::RightBracket => write!(f, "]"),
            TokenKind::Comma => write!(f, ","),
            TokenKind::Dot => write!(f, "."),
            TokenKind::Semicolon => write!(f, ";"),
            TokenKind::Colon => write!(f, ":"),
            TokenKind::Question => write!(f, "?"),
            TokenKind::EndOfFile => write!(f, "EOF"),
            TokenKind::Error(s) => write!(f, "Error({})", s),
        }
    }
}
